name: Update Countdown Image

on:
  schedule:
    - cron: "*/1 * * * *"  # תריץ כל דקה
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: pip install pillow
      - name: Generate image
        run: python countdown.py
      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add countdown.png
          git commit -m "Update countdown"
          git push
